version: "3.6"

services:
  portainer:
    image: portainer/portainer:1.18.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      placement:
        constraints:
          - node.role == manager
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - p_data:/data
    labels:
      type: "management"
    

volumes:
  p_data:
